/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-react-native-hello-world-IAWcZZ-Ca1Z54qrArhEnjJTf1J9bzv4h",
  "version": "2020-11-20"
}

export default ebconfig;